### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by Ryonez** [davidofwatkins/rescroller#2]
Hi there, I have 3 feature requests I'd like to make.

#1: Please make it so a scrollbar size of 0px's hides the scrollbar.

#2: Please add a autohide toggle. (After a set time of page inactivity, it hides the scrollbar.)

#3: Please consider making the option available in a popout window for the extension toolbar. This would make tweaking the settings  breeze and stop us from having to go to another tab to make changes.

I look forward to your thoughts.

**Comment by davidofwatkins** [comment]
These are great suggestions, thanks! I think they should be relatively easy to implement, so I'll see when I can find time (or if anyone else reading this wants to take a crack at it, go for it)!

**Comment by Ryonez** [comment]
Given the changes to Chrome over time, and the experimental transparent scrollbars avaliable, Imma close this request.
