### ISSUE TITLE
Breaks on youtube

### ISSUE THREAD

**Issue by mathsmathsmaths** [davidofwatkins/rescroller#5]
Does not work as expected on youtube. please fix

**Comment by davidofwatkins** [comment]
Hi @mathsmathsmaths, I'm sorry you're having trouble. Could you tell me:

- what OS you're using
- the version of Chrome you're running
- if this started happening recently or if YouTube's always had trouble with Rescroller for you

Additionally, can you elaborate what's happening exactly (ideally with a screenshot)? Thanks!

**Comment by mathsmathsmaths** [comment]
OS: Windows 10
Chrome Version 84
4 months give or take
Expected and current behavior attached. scrollbar1 is current behavior. scrollbar2 is expected behavior (scrollbar handle hover state). As you can see, in the expected behavior the scrollbar does not have the arrows, the scrollbar handle does not have a dark border, the background is dark red instead of dark grey and when the mouse is not hovering over the handle it does not blend into the background.
![scrollbar1](https://user-images.githubusercontent.com/40340216/88205416-5a055d00-cc12-11ea-9c13-220ccc946d55.jpg)
![scrollbar2](https://user-images.githubusercontent.com/40340216/88205432-5ffb3e00-cc12-11ea-942c-80085a60edaa.jpg)

**Comment by mathsmathsmaths** [comment]
OS: Windows 10
Chrome Version 84
4 months give or take
Expected and current behavior attached. scrollbar1 is current behavior. scrollbar2 is expected behavior (scrollbar handle hover state). As you can see, in the expected behavior the scrollbar does not have the arrows, the scrollbar handle does not have a dark border, the background is dark red instead of dark grey and when the mouse is not hovering over the handle it does not blend into the background.
![scrollbar1](https://user-images.githubusercontent.com/40340216/88205416-5a055d00-cc12-11ea-9c13-220ccc946d55.jpg)
![scrollbar2](https://user-images.githubusercontent.com/40340216/88205432-5ffb3e00-cc12-11ea-942c-80085a60edaa.jpg)

**Comment by DelgadoJosh** [comment]
Unknown as to if it works for mathsmathsmaths, but as of April 9th, 2021 I'm having no issues on youtube; it works as expected.

Currently have the default options on Rescroller, Windows 10, Google Chrome Version 89.0.4389.90

**Comment by vitorhonna** [comment]
Works as expected for me.
Windows 10, Opera GX LVL 3 (core: 79.0.4143.60)

**Comment by Nicodemus111** [comment]
im also having it not apply on youtube 1.62.156 Chromium: 121.0.6167.139 (brave)

**Comment by davidofwatkins** [comment]
I'm not sure if it's the only issue here, but at some point YouTube started adding their own scrollbar CSS that conflicted with Rescroller. This is fixed in #19 and should be published sometime later this week.

If you're still seeing issues after the update, please follow-up here!

**Comment by Nicodemus111** [comment]
I totally forgot about this issue tbh its been working for me for like months at this point

**Comment by davidofwatkins** [comment]
YouTube issues should be resolved by v2024.7.7. Closing.
